-- core
require("egor.core.keymaps")
require("egor.plugins-setup")
require("egor.core.options")
require("egor.core.colourscheme")
require("egor.plugins.comment")
require("egor.plugins.nvim-tree")
require("egor.plugins.lualine")
require("egor.plugins.telescope")
-- lsp
require("egor.plugins.nvim-cmp")
require("egor.plugins.lspconfig")
require("egor.plugins.mason")

require("egor.plugins.alpha-nvim")
require("egor.plugins.treesitter")
require("egor.plugins.autopairs")
require("egor.plugins.gitsigns")
require("egor.core.autocmds")
require("egor.plugins.ts-autotags")
