require("egor.plugins-setup")
require("egor.core.options")
require("egor.core.colourscheme")
require("egor.core.keymaps")
require("egor.plugins.comment")
require("egor.plugins.nvim-tree")
require("egor.plugins.nvim-transparent")
require("egor.plugins.lualine")
require("egor.plugins.telescope")
require("egor.plugins.nvim-cmp")
require("egor.plugins.lspconfig")
require("egor.plugins.alpha-nvim")
require("egor.plugins.treesitter")
require("egor.plugins.autopairs")
require("egor.plugins.gitsigns")
-- require("egor.plugins.haskell")
require("egor.plugins.mason")
require("egor.plugins.hardtime")
